[package]
name = "sabaton-mw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyclonedds-rs = "0.3"
cdds_derive = "0.1.0"
async-std = "1.9.0"
futures = "0.3"
thiserror = "1.0"
someip = {git = "https://github.com/sjames/someip.git"}
someip_derive = {git = "https://github.com/sjames/someip.git"}
async-trait = "0.1.31"
serde = "1"
serde_derive = "1"


[dev-dependencies]

interface-example = {git = "https://github.com/sabaton-rs/interface-example.git"}

